# Operation
TLP_ENABLE=1
TLP_DISABLE_DEFAULTS=0
TLP_WARN_LEVEL=3
TLP_MSG_COLORS="91 93 1 92"
TLP_AUTO_SWITCH=2
TLP_PROFILE_AC=PRF
TLP_PROFILE_BAT=BAL
TLP_PROFILE_DEFAULT=BAL

# Audio
SOUND_POWER_SAVE_ON_AC=0
SOUND_POWER_SAVE_ON_BAT=0
SOUND_POWER_SAVE_CONTROLLER=0

# Battery Care
START_CHARGE_THRESH_BAT0=0
STOP_CHARGE_THRESH_BAT0=80
START_CHARGE_THRESH_BAT1=0
STOP_CHARGE_THRESH_BAT1=80
RESTORE_THRESHOLDS_ON_BAT=1

# Disks and Controllers
DISK_DEVICES="nvme0n1 nvme1n1"
DISK_APM_LEVEL_ON_AC="254 254"
DISK_APM_LEVEL_ON_BAT="128 128"
DISK_IOSCHED="mq-deadline mq-deadline"
AHCI_RUNTIME_PM_ON_AC=on
AHCI_RUNTIME_PM_ON_BAT=auto
AHCI_RUNTIME_PM_TIMEOUT=60

# Filesystem
DISK_IDLE_SECS_ON_AC=0
DISK_IDLE_SECS_ON_BAT=2
MAX_LOST_WORK_SECS_ON_AC=15
MAX_LOST_WORK_SECS_ON_BAT=30

# Kernel
NMI_WATCHDOG=0

# Networks
WIFI_PWR_ON_AC=off
WIFI_PWR_ON_BAT=off
WOL_DISABLE=N

# Platform
PLATFORM_PROFILE_ON_AC=performance
PLATFORM_PROFILE_ON_BAT=balanced
PLATFORM_PROFILE_ON_SAV=balanced
MEM_SLEEP_ON_AC=deep
MEM_SLEEP_ON_BAT=deep

# Processor
CPU_DRIVER_OPMODE_ON_AC=active
CPU_DRIVER_OPMODE_ON_BAT=active
CPU_DRIVER_OPMODE_ON_SAV=active
CPU_SCALING_GOVERNOR_ON_AC=performance
CPU_SCALING_GOVERNOR_ON_BAT=powersave
CPU_SCALING_GOVERNOR_ON_SAV=powersave
CPU_ENERGY_PERF_POLICY_ON_AC=performance
CPU_ENERGY_PERF_POLICY_ON_BAT=balance_power
CPU_ENERGY_PERF_POLICY_ON_SAV=power
CPU_MIN_PERF_ON_AC=0
CPU_MAX_PERF_ON_AC=100
CPU_MIN_PERF_ON_BAT=0
CPU_MAX_PERF_ON_BAT=75
CPU_MIN_PERF_ON_SAV=0
CPU_MAX_PERF_ON_SAV=50
CPU_BOOST_ON_AC=1
CPU_BOOST_ON_BAT=1
CPU_BOOST_ON_SAV=0
CPU_HWP_DYN_BOOST_ON_AC=1
CPU_HWP_DYN_BOOST_ON_BAT=1
CPU_HWP_DYN_BOOST_ON_SAV=0

# Radio Device Wizard
DEVICES_TO_DISABLE_ON_LAN_CONNECT="wifi"
DEVICES_TO_ENABLE_ON_LAN_DISCONNECT="wifi"

# Runtime Power Management and ASPM
RUNTIME_PM_ON_AC=on
RUNTIME_PM_ON_BAT=auto
PCIE_ASPM_ON_AC=performance
PCIE_ASPM_ON_BAT=default
PCIE_ASPM_ON_SAV=powersave

# USB
USB_AUTOSUSPEND=0
