#!/usr/bin/bash

DISK="$(realpath /dev/disk/by-id/ata-SAMSUNG_MZVLB256HAHQ-000_S45UNX0N104146)"
BOOT="${DISK}1"
ROOT="${DISK}2"

blkdiscard -f -z ${DISK}

sgdisk -I -n 1:0:+1G -t 1:ef00 -c 1:'BOOT' -N 2 -t 2:8304 -c 2:'root' ${DISK}

mkfs.fat -F 32 -n 'BOOT' ${BOOT}

mkfs.btrfs -f -L 'root' -d single -m single ${ROOT}

mount -o 'compress=zstd' ${ROOT} /mnt
btrfs subvolume create /mnt/@ /mnt/@var /mnt/@home /mnt/@snapshots
umount /mnt

mount -o 'compress=zstd,subvol=/@' ${ROOT} /mnt
mount -m -o 'compress=zstd,subvol=/@var' ${ROOT} /mnt/var
mount -m -o 'compress=zstd,subvol=/@home' ${ROOT} /mnt/home
mount -m -o 'compress=zstd,subvol=/@snapshots' ${ROOT} /mnt/.snapshots
mount -m -o 'nosuid,nodev,noexec,nosymfollow,fmask=0177,dmask=0077' ${BOOT} /mnt/boot

chattr +C /mnt/var

pacstrap -KM /mnt base iptables mkinitcpio

genfstab -U /mnt | tee -a /mnt/etc/fstab

install -m 0777 /tmp/perfect/medium_install /mnt/usr/local/bin/
cp -a /tmp/perfect/configs /mnt/opt/

ln -f -s /run/systemd/resolve/stub-resolv.conf /mnt/etc/resolv.conf

arch-chroot -S /mnt /usr/local/bin/medium_install

rm -f /mnt/usr/local/bin/medium_install

install -m 0777 /tmp/perfect/medium_setup /mnt/usr/local/bin/
install -m 0777 /tmp/perfect/medium_user /mnt/usr/local/bin/

pkill gpg-agent
umount -R /mnt
systemctl reboot --firmware-setup
