#!/usr/bin/bash

set -a -e -u

umount /.snapshots
rm -f -r /.snapshots
snapper -c root create-config /
snapper -c root set-config 'ALLOW_GROUPS=wheel' 'SYNC_ACL=yes' 'TIMELINE_LIMIT_HOURLY=3' 'TIMELINE_LIMIT_DAILY=3' 'TIMELINE_LIMIT_WEEKLY=4' 'TIMELINE_LIMIT_MONTHLY=0' 'TIMELINE_LIMIT_YEARLY=0' 'NUMBER_LIMIT=15'
snapper -c home create-config /home
snapper -c home set-config 'ALLOW_GROUPS=wheel' 'SYNC_ACL=yes' 'TIMELINE_LIMIT_HOURLY=3' 'TIMELINE_LIMIT_DAILY=3' 'TIMELINE_LIMIT_WEEKLY=4' 'TIMELINE_LIMIT_MONTHLY=0' 'TIMELINE_LIMIT_YEARLY=0' 'NUMBER_LIMIT=15'
btrfs subvolume delete /.snapshots
mkdir /.snapshots
systemctl daemon-reload
mount -a

waydroid init -s GAPPS

systemctl enable snapper-boot.timer snapper-cleanup.timer waydroid-container.service

warp-cli --accept-tos generate-completions bash | tee /usr/share/bash-completion/completions/warp-cli

sed -i -e '/archive.archlinux.org/d' /etc/pacman.d/mirrorlist

rm -f -r /opt/configs /usr/local/bin/medium_setup
