#!/usr/bin/bash

set -a -e -u

sudo umount /.snapshots
sudo rm -f -r /.snapshots
sudo snapper -c root create-config /
sudo snapper -c root set-config 'ALLOW_GROUPS=wheel' 'SYNC_ACL=yes' 'TIMELINE_LIMIT_HOURLY=3' 'TIMELINE_LIMIT_DAILY=3' 'TIMELINE_LIMIT_WEEKLY=4' 'TIMELINE_LIMIT_MONTHLY=0' 'TIMELINE_LIMIT_YEARLY=0' 'NUMBER_LIMIT=15'
sudo snapper -c home create-config /home
sudo snapper -c home set-config 'ALLOW_GROUPS=wheel' 'SYNC_ACL=yes' 'TIMELINE_LIMIT_HOURLY=3' 'TIMELINE_LIMIT_DAILY=3' 'TIMELINE_LIMIT_WEEKLY=4' 'TIMELINE_LIMIT_MONTHLY=0' 'TIMELINE_LIMIT_YEARLY=0' 'NUMBER_LIMIT=15'
sudo btrfs subvolume delete /.snapshots
sudo mkdir /.snapshots
sudo systemctl daemon-reload
sudo mount -a

yes | warp-cli registration new
warp-cli generate-completions bash | sudo tee /usr/share/bash-completion/completions/warp-cli

sudo waydroid init -s GAPPS

sudo systemctl enable snapper-boot.timer snapper-cleanup.timer waydroid-container.service

systemctl --user enable warp-taskbar.service

sudo sed -i -e '/archive.archlinux.org/d' /etc/pacman.d/mirrorlist

sudo rm -f -r /opt/configs /usr/local/bin/medium_setup
