#!/usr/bin/bash

set -a -e -u

DISK="$(realpath '/dev/disk/by-id/nvme-nvme.1e4b-30303335363230303030303532-4e452d3154422032323432-00000001')"
DISKAUX="$(realpath '/dev/disk/by-id/nvme-eui.e8238fa6bf530001001b448b47f32f0c')"
ROOT="${DISK}p2"
AUX="${DISKAUX}p1"

sudo systemd-cryptenroll --tpm2-device /dev/tpmrm0 --tpm2-pcrs 7 "${ROOT}"
sudo systemd-cryptenroll --tpm2-device /dev/tpmrm0 --tpm2-pcrs 7 "${AUX}"

sudo umount /.snapshots
sudo rm -f -r /.snapshots
sudo snapper -c root create-config /
sudo snapper -c root set-config 'ALLOW_GROUPS=wheel' 'SYNC_ACL=yes' 'TIMELINE_LIMIT_HOURLY=3' 'TIMELINE_LIMIT_DAILY=3' 'TIMELINE_LIMIT_WEEKLY=4' 'TIMELINE_LIMIT_MONTHLY=0' 'TIMELINE_LIMIT_YEARLY=0' 'NUMBER_LIMIT=15' 'NUMBER_CLEANUP=yes'
sudo snapper -c home create-config /home
sudo snapper -c home set-config 'ALLOW_GROUPS=wheel' 'SYNC_ACL=yes' 'TIMELINE_LIMIT_HOURLY=3' 'TIMELINE_LIMIT_DAILY=3' 'TIMELINE_LIMIT_WEEKLY=4' 'TIMELINE_LIMIT_MONTHLY=0' 'TIMELINE_LIMIT_YEARLY=0' 'NUMBER_LIMIT=15' 'NUMBER_CLEANUP=yes'
sudo btrfs subvolume delete /.snapshots
sudo mkdir /.snapshots
sudo systemctl daemon-reload
sudo mount -a

sudo waydroid init -s GAPPS

sudo systemctl enable snapper-boot.timer snapper-cleanup.timer snapshot_sdboot.service waydroid-container.service

warp-cli --accept-tos registration new
warp-cli generate-completions bash | sudo tee /usr/share/bash-completion/completions/warp-cli

sudo sed -i -e '/archive.archlinux.org/d' /etc/pacman.d/mirrorlist

sudo rm -f -r /opt/configs /usr/local/bin/perfect_setup
