#!/usr/bin/bash

set -a -e -o pipefail -u

DISK="$(realpath '/dev/disk/by-id/nvme-nvme.1e4b-30303335363230303030303532-4e452d3154422032323432-00000001')"
DISKAUX="$(realpath '/dev/disk/by-id/nvme-eui.e8238fa6bf530001001b448b47f32f0c')"
BOOT="${DISK}p1"
ROOT="${DISK}p2"
AUX="${DISKAUX}p1"

genUUID() {
	UUID="$(< /proc/sys/kernel/random/uuid)"
	UUID="${1}${UUID:2}"
	printf '%s\n' "${UUID}"
}

genID() {
	ID="$(< /proc/sys/kernel/random/uuid)"
	ID="b7${ID:0:6}"
	printf '%s\n' "${ID}"
}

nvme format "${DISK%n*}" -f -n 1 -l 0 -s 1 -r
nvme format "${DISKAUX%n*}" -f -n 1 -l 0 -s 1 -r
partprobe "${DISK}" "${DISKAUX}"

sgdisk -U "$(genUUID 'd5')" -I -n 1:0:+1G -t 1:ef00 -c 1:'BOOT' -u 1:"$(genUUID 'd9')" -N 2 -t 2:8304 -c 2:'root' -u 2:"$(genUUID 'd9')" "${DISK}"
sgdisk -U "$(genUUID 'd5')" -I -N 1 -t 1:8304 -c 1:'aux' -u 1:"$(genUUID 'd9')" "${DISKAUX}"

mkfs.fat -I -F 32 -i "$(genID)" -n 'BOOT' "${BOOT}"

read -p 'Enter Passphrase: ' -r PASSWD

printf '%s\n' "${PASSWD}" | cryptsetup luksFormat --label 'root' --uuid "$(genUUID 'ec')" -q "${ROOT}"
printf '%s\n' "${PASSWD}" | cryptsetup luksFormat --label 'aux' --uuid "$(genUUID 'ec')" -q "${AUX}"

printf '%s\n' "${PASSWD}" | cryptsetup open --allow-discards --persistent "${ROOT}" root
printf '%s\n' "${PASSWD}" | cryptsetup open --allow-discards --persistent "${AUX}" aux

mkfs.btrfs -f -L 'root' -d raid0 -m raid1 -U "$(genUUID 'bf')" /dev/mapper/root /dev/mapper/aux

mount -o 'compress=zstd' /dev/mapper/root /mnt
btrfs subvolume create /mnt/@ /mnt/@var /mnt/@home /mnt/@snapshots
umount /mnt

mount -o 'compress=zstd,subvol=/@' /dev/mapper/root /mnt
mount -m -o 'compress=zstd,subvol=/@var' /dev/mapper/root /mnt/var
mount -m -o 'compress=zstd,subvol=/@home' /dev/mapper/root /mnt/home
mount -m -o 'compress=zstd,subvol=/@snapshots' /dev/mapper/root /mnt/.snapshots
mount -m -o 'nosuid,nodev,noexec,nosymfollow,fmask=0177,dmask=0077' "${BOOT}" /mnt/boot

chattr +C /mnt/var

pacstrap -C /root/perfect/pacman.d/pacman.conf -K -M /mnt base iptables mkinitcpio

genfstab -U /mnt | tee -a /mnt/etc/fstab

install -m 0777 /root/perfect/perfect_install /mnt/usr/local/bin/
install -m 0777 /root/perfect/perfect_setup /mnt/usr/local/bin/
install -m 0777 /root/perfect/snapshot_sdboot /mnt/usr/local/bin/

install -m 0777 /root/perfect/user_config /mnt/usr/local/bin/
install -m 0777 /root/perfect/git_keys_config /mnt/usr/local/bin/

cp -a /root/perfect/configs /mnt/opt/

ln -f -s /run/systemd/resolve/stub-resolv.conf /mnt/etc/resolv.conf

arch-chroot -S /mnt /usr/local/bin/perfect_install
arch-chroot -S -u am /mnt /usr/local/bin/user_config

rm -f /mnt/usr/local/bin/perfect_install /mnt/usr/local/bin/user_config

pkill -9 -u root gpg-agent
umount -R /mnt
cryptsetup close root
cryptsetup close aux
systemctl poweroff --firmware-setup
