#!/usr/bin/bash

sudo perfect_setup
sudo rm -f /usr/local/bin/perfect_setup

sed -i -e '/^PS1\b/d' ${HOME}/.bashrc
printf '%s\n' "PS1=' \[\e[33;1;4m\]⮜ \A | \u | \w | \$? ⮞\[\e[0m\] '" | tee -a ${HOME}/.bashrc

printf '%s\n' '' 'set show-all-if-ambiguous on' 'set colored-stats on' 'set visible-stats on' 'set mark-symlinked-directories on' 'set colored-completion-prefix on' 'set menu-complete-display-prefix on' 'set echo-control-characters off' '' '"\e[A": history-search-backward' '"\e[B": history-search-forward' | tee -a ${HOME}/.inputrc

gsettings set org.gnome.desktop.interface font-name 'Sans 10'
gsettings set org.gnome.desktop.interface document-font-name 'Serif 10'
gsettings set org.gnome.desktop.interface monospace-font-name 'Monospace 10'
gsettings set org.gnome.desktop.interface gtk-theme 'Adwaita-dark'
gsettings set org.gnome.desktop.interface gtk-enable-primary-paste true
gsettings set org.gnome.desktop.media-handling automount false
gsettings set org.gnome.desktop.media-handling automount-open false
curl -L -o "${XDG_DATA_HOME}/backgrounds/default.jpg" -R -s 'https://unsplash.com/photos/24Thc8IlubM/download?force=true&w=1920'
gsettings set org.gnome.desktop.background picture-uri "file://${XDG_DATA_HOME}/backgrounds/default.jpg"
gsettings set org.gnome.desktop.background picture-uri-dark "file://${XDG_DATA_HOME}/backgrounds/default.jpg"
gsettings set org.gnome.SessionManager logout-prompt false
gsettings set org.gnome.settings-daemon.plugins.housekeeping donation-reminder-enabled false
gsettings set org.gnome.shell disable-extension-version-validation true
gnome-extensions enable 'appindicatorsupport@rgcjonas.gmail.com'

printf '%s\n' 'font-family = monospace' 'font-size = 10' 'theme = light:Gruvbox Material Light,dark:Gruvbox Material Dark' 'fullscreen = true' | tee -a ${XDG_CONFIG_HOME}/ghostty/config
mkdir -p ${XDG_CONFIG_HOME}/easyeffects/output/
git clone --depth 1 'https://github.com/BayouGuru67/Linux_Audio.git' ${XDG_CONFIG_HOME}/easyeffects/output/

ssh-keygen
gpg --full-gen-key
GPGKEY="$(gpg -K --keyid-format long | grep 'sec' | cut -d '/' -f 2 | cut -d ' ' -f 1)"
gpg -a -o "${HOME}/.gnupg/public-keys.d/am.asc" --export ${GPGKEY}

git config set --global user.name 'AlaEldin Mohamed'
git config set --global user.email 'aeiedamo@gmail.com'
git config set --global init.defaultBranch 'main'
git config set --global user.signingkey ${GPGKEY}
git config set --global commit.gpgsign true
git config set --global tag.gpgSign true

git clone --depth 1 'https://aur.archlinux.org/yay-bin.git' /tmp/yay-bin
yes | makepkg -sicD /tmp/yay-bin

yes | yay -Syu --needed adwaita-qt6 google-chrome intel-compute-runtime-legacy-bin otf-ibm-plex ttf-apple-emoji

printf '%s\n' '--enable-features=AcceleratedVideoDecodeLinuxGL,TouchpadOverscrollHistoryNavigation' | tee ${XDG_CONFIG_HOME}/chrome-flags.conf

sudo rm -f /usr/local/bin/perfect_user
