#!/usr/bin/bash

set -e -u -o pipefail

sudo perfect_setup
sudo rm -f /usr/local/bin/perfect_setup

mkdir -p "${HOME}/.local/bin"

sed -i -e '/^PS1\b/d' "${HOME}/.bashrc"
printf '%s\n' "PS1=' \[\e[33;1;4m\]⮜ \A | \u | \w | \$? ⮞\[\e[0m\] '" | tee -a "${HOME}/.bashrc"

printf '%s\n' '"\e[A": history-search-backward' '"\e[B": history-search-forward' '' 'set bell-style none' 'set echo-control-characters off' 'set show-all-if-ambiguous on' 'set colored-stats on' 'set visible-stats on' 'set mark-symlinked-directories on' 'set completion-ignore-case on' 'set completion-map-case on' 'set colored-completion-prefix on' 'set menu-complete-display-prefix on' 'set revert-all-at-newline on' '$if Bash' 'Tab: menu-complete' '$endif' | tee -a "${HOME}/.inputrc"

gsettings set org.gnome.desktop.interface gtk-theme 'Adwaita-dark'
gsettings set org.gnome.desktop.interface gtk-enable-primary-paste true
gsettings set org.gnome.desktop.media-handling automount false
gsettings set org.gnome.desktop.media-handling automount-open false
gsettings set org.gnome.SessionManager logout-prompt false
gsettings set org.gnome.settings-daemon.plugins.housekeeping donation-reminder-enabled false
gsettings set org.gnome.shell disable-extension-version-validation true
gsettings set org.gnome.nautilus.preferences date-time-format 'detailed'
gsettings set org.gnome.nautilus.preferences default-folder-viewer 'list-view'
gsettings set org.gnome.nautilus.preferences show-create-link true
gsettings set org.gnome.nautilus.preferences show-delete-permanently true
gsettings set org.gtk.gtk4.Settings.FileChooser sort-directories-first true
gsettings set ca.desrt.dconf-editor.Settings show-warning false

printf '%s\n' '--enable-features=AcceleratedVideoDecodeLinuxGL,TouchpadOverscrollHistoryNavigation' | tee "${XDG_CONFIG_HOME}/chrome-flags.conf"

printf '%s\n' 'font-family = monospace' 'font-size = 10' 'theme = light:Gruvbox Material Light,dark:Gruvbox Material Dark' 'window-decoration = none' 'maximize = true' | tee -a "${XDG_CONFIG_HOME}/ghostty/config"

mkdir -p "${XDG_CONFIG_HOME}/easyeffects/output/"
git clone --depth 1 'https://github.com/BayouGuru67/Linux_Audio.git' "${XDG_CONFIG_HOME}/easyeffects/output/"

mkdir -p "${XDG_DATA_HOME}/images"
chattr +C "${XDG_DATA_HOME}/images"

yes | yay -Syu --needed hunspell-ar otf-ibm-plex ttf-apple-emoji || true

sudo rm -f -r /opt/configs
sudo rm -f /usr/local/bin/perfect_user
