#!/usr/bin/bash

set -a -e

cd "${HOME}"

. /etc/profile

mkdir -p "${XDG_CACHE_HOME}" "${XDG_CONFIG_HOME}/fontconfig" "${XDG_CONFIG_HOME}/ghostty" "${XDG_DATA_HOME}/easyeffects/output" "${XDG_STATE_HOME}" "${HOME}/.local/bin"

yay -Syu --needed --noconfirm gnome-shell-extension-just-perfection-desktop hunspell-ar otf-ibm-plex ttf-apple-emoji

cp /etc/fonts/local.conf "${XDG_CONFIG_HOME}/fontconfig/fonts.conf"

sed -i -e '/^PS1\b/d' "${HOME}/.bashrc"
printf '%s\n' "PS1=' \[\e[33;1;4m\]⮜ \A | \u | \w | \$? ⮞\[\e[0m\] '" | tee -a "${HOME}/.bashrc"

printf '%s\n' '"\e[A": history-search-backward' '"\e[B": history-search-forward' '' 'set bell-style none' 'set echo-control-characters off' 'set show-all-if-ambiguous on' 'set colored-stats on' 'set visible-stats on' 'set mark-symlinked-directories on' 'set completion-ignore-case on' 'set completion-map-case on' 'set colored-completion-prefix on' 'set menu-complete-display-prefix on' 'set revert-all-at-newline on' '$if Bash' 'Tab: menu-complete' '$endif' | tee -a "${HOME}/.inputrc"

printf '%s\n' '--enable-features=AcceleratedVideoDecodeLinuxGL,TouchpadOverscrollHistoryNavigation' | tee "${XDG_CONFIG_HOME}/chrome-flags.conf"

printf '%s\n' 'font-family = monospace' 'font-size = 10' 'theme = light:Gruvbox Material Light,dark:Gruvbox Material Dark' 'window-decoration = none' 'maximize = true' | tee -a "${XDG_CONFIG_HOME}/ghostty/config"

git clone --depth 1 'https://github.com/BayouGuru67/Linux_Audio.git' "${XDG_DATA_HOME}/easyeffects/output/"

mkdir -p "${XDG_DATA_HOME}/images"
chattr +C "${XDG_DATA_HOME}/images"
